### ISSUE TITLE
App can't open

### ISSUE THREAD

**Issue by AITuring** [foamzou/ITraffic-monitor-for-mac#1]
![image](https://user-images.githubusercontent.com/18332608/120952710-2e358c00-c77e-11eb-857e-f9c03ddcd7e9.png)

**Comment by foamzou** [comment]
Try to execute the command in terminal, it will allow open app which download from anywhere
`sudo spctl --master-disable`

Another hand, I would publish the app to homebrew later,  maybe it would fix it while installing by brew.
