### ISSUE TITLE
nettop-line run in X86 mode in Apple Chip Mac

### ISSUE THREAD

**Issue by itszhengkun** [foamzou/ITraffic-monitor-for-mac#10]
found out ITraffic-monitor-for-mac use nettop-line excutable to monitor traffic,
but nettop-line binary is in X86
![image](https://user-images.githubusercontent.com/4617731/231398549-11cb5592-26b0-4c9e-bca0-b95de1bc4253.png)

**Comment by itszhengkun** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/4617731/231399206-6ec7e488-829f-4fd8-86a2-da6bb99233d2.png">

**Comment by foamzou** [comment]
Yes. But it runs well, right? May the nettop syscall is nothing to do with the platform.
