### ISSUE TITLE
能否可以调整这个字体，字体稍微大了点，和旁边的太不协调了

### ISSUE THREAD

**Issue by Timmy-y** [foamzou/ITraffic-monitor-for-mac#12]

**Comment by foamzou** [comment]
指的是 menu bar 的速率字体吗？大一点好看一些。
目前业余没有太多时间，不会提供偏好设置。如果你可以自己编译的话，我可以看下在哪里修改代码。

**Comment by Timmy-y** [comment]
我自己已经编译了，可以调整大小，但是有个问题请假一下，就是整个图标在menubar上的占的宽度比较宽，不知道在哪里可以调整，左右间距与其他比如QQ、微信这些图标相距很远，留了很大的空白




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "foamzou/ITraffic-monitor-for-mac"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月31日(星期一) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [foamzou/ITraffic-monitor-for-mac] 能否可以调整这个字体，字体稍微大了点，和旁边的太不协调了 (Issue #12)





 
指的是 menu bar 的速率字体吗？大一点好看一些。
 目前业余没有太多时间，不会提供偏好设置。如果你可以自己编译的话，我可以看下在哪里修改代码。

**Comment by foamzou** [comment]
这两块可以调调。上图是总大小，下图是3块元素的宽度和 padding
<img width="870" alt="image" src="https://github.com/foamzou/ITraffic-monitor-for-mac/assets/9295077/54917049-ffc5-4121-b34b-6c6e62922ead">
<img width="821" alt="image" src="https://github.com/foamzou/ITraffic-monitor-for-mac/assets/9295077/c1ce1be5-d188-414a-a501-30780bbf0b28">

**Comment by Timmy-y** [comment]
完美
<img width="425" alt="image" src="https://github.com/foamzou/ITraffic-monitor-for-mac/assets/62916836/63537ad7-2410-4d16-8cc0-3677cff899cb">

**Comment by foamzou** [comment]
Cool. 请问当数值字符串宽度变长后，会有显示问题不？
如果没有问题的话，可以帮忙提个 PR 吗？

**Comment by Timmy-y** [comment]
测试到3位，比如312.3KB/s，能正常显示，等我再确认下，忙完了，我提上去

**Comment by foamzou** [comment]
Updated in #13
