### ISSUE TITLE
Not work for MAC version 14.1 M1

### ISSUE THREAD

**Issue by fengshenyanyi** [foamzou/ITraffic-monitor-for-mac#15]
![WX20231105-230628@2x](https://github.com/foamzou/ITraffic-monitor-for-mac/assets/19420180/ffb8e92d-a98a-4728-b69b-d41e372d0586)
![WX20231105-230612@2x](https://github.com/foamzou/ITraffic-monitor-for-mac/assets/19420180/a34e78e1-029f-4301-8851-de3b57d2c2e8)

**Comment by fengshenyanyi** [comment]
Ok, thanks for your reply, it works fine now.

**Comment by foamzou** [comment]
Great! What did you do to make it work fine? @fengshenyanyi
