### ISSUE TITLE
如果开了代理，流量统计会走到代理那边

### ISSUE THREAD

**Issue by wfh1988** [foamzou/ITraffic-monitor-for-mac#16]
![image](https://github.com/foamzou/ITraffic-monitor-for-mac/assets/37572509/faf6964c-458e-4afe-b645-7e44c79a6fbb)

如果开了代理，流量统计会走到代理那边（ClashX），有办法不走代理吗（实际为Edge的流量）？
（这个需求能实现吗？弱弱的问一下）

**Comment by foamzou** [comment]
你好。无法实现，该应用最底层调用的是 mac 命令行 nettop。
https://github.com/foamzou/ITraffic-monitor-for-mac/blob/main/ITrafficMonitorForMac/Network.swift#L30
从 nettop -h 来看，没有哪个参数能够实现这个需求

**Comment by wfh1988** [comment]
> 你好。无法实现，该应用最底层调用的是 mac 命令行 nettop。 https://github.com/foamzou/ITraffic-monitor-for-mac/blob/main/ITrafficMonitorForMac/Network.swift#L30 从 nettop -h 来看，没有哪个参数能够实现这个需求

明白了，谢谢！

**Comment by foamzou** [comment]
你好，已经支持该 Feature。全新版本上架 App Store 了，欢迎下载试用。

https://bytetally.app
