### ISSUE TITLE
M3 Max ver 14.2.1 打不开，没反应

### ISSUE THREAD

**Issue by X-Bird** [foamzou/ITraffic-monitor-for-mac#17]
M3 Max ver 14.2.1 打不开，没反应。
已经隐私放行打开，进程在，但是没有任何界面或者menu bar按扭出现。
只能命令行kill掉退出。

**Comment by foamzou** [comment]
刘海屏挺占用 menubar 长度的，猜测是空间不够。可以移除不常用的 icon 或者调整 icon 顺粗。或者考虑使用 Bartender 这类 app 解决
