### ISSUE TITLE
not work in my device

### ISSUE THREAD

**Issue by kitety** [foamzou/ITraffic-monitor-for-mac#18]
behavior
<img width="348" alt="image" src="https://github.com/foamzou/ITraffic-monitor-for-mac/assets/22906933/05bf6387-6c53-486a-a710-0c5c65b8a68e">
system info
<img width="181" alt="image" src="https://github.com/foamzou/ITraffic-monitor-for-mac/assets/22906933/79af6d7d-925f-460e-902f-3e83de97be52">

**Comment by foamzou** [comment]
Try to quit and reopen the app.

**Comment by kitety** [comment]
I have tried several times, but it does not work. I will try tomorrow.

**Comment by kitety** [comment]
it does not work after i reopen the app

**Comment by kitety** [comment]
ok is worked after I installed rosetta2.
