### ISSUE TITLE
您使用的是 macOS 10.14.6。该应用程序要求 macOS 10.15 或更高版本。

### ISSUE THREAD

**Issue by ltto** [foamzou/ITraffic-monitor-for-mac#2]
![image](https://user-images.githubusercontent.com/24884691/120997403-bedd8d80-c7b9-11eb-8419-8cb791ace374.png)
![image](https://user-images.githubusercontent.com/24884691/120997419-c1d87e00-c7b9-11eb-932f-6978a5fe537d.png)

可以支持一下吗

**Comment by foamzou** [comment]
抱歉，暂时没有支持的计划
