### ISSUE TITLE
demand

### ISSUE THREAD

**Issue by bdragonh** [foamzou/ITraffic-monitor-for-mac#3]
Hello, can you count the total traffic information uploaded and downloaded

**Comment by foamzou** [comment]
Sure. I have a plan to statistic the upload/download traffic per app and per interval(hour/day/month).

The feature has been added to my to-do list a few months ago and developed some. But does not continue do this recent months. The feature may release a little later.

**Comment by bdragonh** [comment]
Thank you. I'm looking forward to the new version
