### ISSUE TITLE
macOS 13.0 not work.

### ISSUE THREAD

**Issue by kitety** [foamzou/ITraffic-monitor-for-mac#5]
The application does not display the network speed on mac OS 13.0
Would you mind fixing it?

![image](https://user-images.githubusercontent.com/22906933/197814661-1f4703ba-7514-4fe1-ad2e-c5a6cab0e2fa.png)

**Comment by foamzou** [comment]
Will check it later

**Comment by foamzou** [comment]
And please let me know what's the mac you are using. M1 M2 ?

The software seems not to support the ARM now.

@kitety

**Comment by kitety** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/22906933/198292684-8012beea-da1d-4ab2-9902-e6f664266277.png">

But it can run well at previous one  macOS version.

**Comment by foamzou** [comment]
@kitety 
Feel free to upgrade the software to v0.1.5. There are 2 way could be upgrade:
1. Download the file in the latest release https://github.com/foamzou/ITraffic-monitor-for-mac/releases/tag/v0.1.5
2. Once the brew PR be merged. You can execute `brew update && brew upgrade itraffic` to upgrade

Please let me know if working fine after upgrade to the latest version.

Thanks

**Comment by kitety** [comment]
OK，Thanks a lot.

**Comment by kitety** [comment]
Sorry,it does not work
![image](https://user-images.githubusercontent.com/22906933/198782802-9b61105b-c555-40f4-a5d3-b9297a465502.png)

**Comment by foamzou** [comment]
I see. Due to the nettop-line segment fault after wrap by upx. Has been fixed and upload the application to https://github.com/foamzou/ITraffic-monitor-for-mac/releases/tag/v0.1.5

But it seems the system menu bar would hide the itraffic menu on MacOS 13.0, will fix it when I free.

@kitety

**Comment by kitety** [comment]
ok, thanks a lot.

**Comment by kitety** [comment]
good it works
