### ISSUE TITLE
打包有问题?

### ISSUE THREAD

**Issue by fbion** [foamzou/ITraffic-monitor-for-mac#6]
https://github.com/foamzou/ITraffic-monitor-for-mac/releases/download/v0.1.5/ITraffic-v0.1.5.zip

ls -l ITraffic.app/Contents/MacOS/
total 816
drwxr-xr-x@ 3 xxx  staff      96 10 28 13:24 ./
drwxr-xr-x@ 7 xxx  staff     224 10 28 13:24 ../
-rw-rw-r--@ 1 xxx  staff  416256 10 28 13:24 ITraffic

应用程序“ITraffic.app”无法打开。
ITraffic没有x权限?

**Comment by foamzou** [comment]
Thanks feedback the issue.

The zip file was zipped by github before, not sure why it's broken.

I zipped the application on my local machine and upload it just now. And it's working fine now.

@fbion 

And just curious that why you got the update of the repo so fast?

**Comment by fbion** [comment]
> 

因为我出国线路好?
