### ISSUE TITLE
display panel's position has offset

### ISSUE THREAD

**Issue by MartinDai** [foamzou/ITraffic-monitor-for-mac#8]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/11816720/215300093-57d1f154-6347-40a6-a880-0e2f1ef6f2d4.png">

<img width="526" alt="image" src="https://user-images.githubusercontent.com/11816720/215300198-deb84867-14c9-4f26-b798-eb69ba79b12b.png">

**Comment by echogroot01** [comment]
+1

**Comment by foamzou** [comment]
@MartinDai @echogroot01 @awx-henry-liu

Fixed the bug. Feel free to upgrade the software to v0.1.6. There are two way to upgrade:

- `brew update && brew upgrade itraffic`
- Download the file in the latest release https://github.com/foamzou/ITraffic-monitor-for-mac/releases/tag/v0.1.6
