### ISSUE TITLE
menubar position has offset

### ISSUE THREAD

**Issue by awx-henry-liu** [foamzou/ITraffic-monitor-for-mac#9]
<img width="358" alt="image" src="https://user-images.githubusercontent.com/79567572/225548184-79612d8f-c720-4258-87e7-c57ca4bb5b02.png">

<img width="242" alt="image" src="https://user-images.githubusercontent.com/79567572/225548263-3dc63ccf-daf9-4ab2-831d-76a60fede187.png">

**Comment by foamzou** [comment]
duplicate of #8
